branches:
  only:
  - master
language: python
python:
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
services:
  - redis-server
  - rabbitmq
  - mysql
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
  - mysql -e 'CREATE DATABASE FFXIV_DEV;'
  - mysql -u root -e "CREATE USER 'FFXIV_DEV'@'localhost' IDENTIFIED BY 'PASSWORD';"
  - mysql -u root -e "GRANT ALL ON FFXIV_DEV.* TO 'FFXIV_DEV'@'localhost';"
  - mv FFXIV/settings_example.py FFXIV/settings.py
  - python manage.py makemigrations ffxivbot
  - python manage.py makemigrations
  - python manage.py migrate
# command to run tests
script:
  - python manage.py check

after_success:
  - bash <(curl -s https://codecov.io/bash)
